services:
#    quizzy.example:
#        class: QuizzyBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    quizzy.image_service:
      class: QuizzyBundle\Service\ImageService
      arguments: ['@service_container', '@doctrine.orm.entity_manager']

    quizzy.quiz_service:
      class: QuizzyBundle\Service\QuizService
      arguments: ['@doctrine.orm.entity_manager']

